name: AnalyticaCore AI - Azure Deployment

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch: # Allow manual trigger

env:
  AZURE_RESOURCE_GROUP: rg-analyticacore-prod
  AZURE_LOCATION: eastus2

jobs:
  # Deploy Static Web App
  static-web-app:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build And Deploy Static Web App
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "/"
          api_location: ""
          output_location: "/website"
          skip_app_build: true
          skip_api_build: true
          skip_deploy_on_missing_secrets: true
          
  # Deploy Infrastructure (if needed)
  infrastructure:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && false  # Disabled for now
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy Bicep template
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          resourceGroupName: ${{ env.AZURE_RESOURCE_GROUP }}
          template: ./infra/main.bicep
          parameters: environmentName=prod location=eastus2
          failOnStdErr: false`
          